server:      true
auto:        true
server_port: 4000
pygments:    false
permalink:   /:categories/:title/

markdown:    rdiscount
rdiscount:
  extensions: [smart]

exclude:
  - config.rb
  - deploy
  - README.mkd
  - grid-image
