highlighter:  false
permalink: /writing/:title/
markdown:  kramdown
url:       http://danhorst.github.io
tag_page:  /tags/
ga_token:  UA-28083204-3

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
